#!/usr/bin/env bash
set -x
# This shell script is generated by overlayfs-tools on Fri Oct 31 20:02:22 2025

LOWERDIR='/mnt/winOverlay/SSD2WinLower'
UPPERDIR='/mnt/winOverlay/SSD2WinUpper'
chmod --reference "$UPPERDIR"'' "$LOWERDIR"''
rmdir "$UPPERDIR"'/SteamLibrary'
