#!/usr/bin/env bash
set -x
# This shell script is generated by overlayfs-tools on Mon Oct 20 13:35:23 2025

LOWERDIR='/mnt/winOverlay/SSDWinLower'
UPPERDIR='/mnt/winOverlay/SSDWinUpper'
chmod --reference "$UPPERDIR"'' "$LOWERDIR"''
rmdir "$UPPERDIR"'/Media/Games/Steam/steamapps/downloading'
mv -T "$UPPERDIR"'/Media/Games/Steam/steamapps/common/Zortch' "$LOWERDIR"'/Media/Games/Steam/steamapps/common/Zortch'
rmdir "$UPPERDIR"'/Media/Games/Steam/steamapps/common'
rm -rf "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2623190.acf'
mv -T "$UPPERDIR"'/Media/Games/Steam/steamapps/appmanifest_2623190.acf' "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2623190.acf'
rm -rf "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2443360.acf'
mv -T "$UPPERDIR"'/Media/Games/Steam/steamapps/appmanifest_2443360.acf' "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2443360.acf'
rm -rf "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2947440.acf'
mv -T "$UPPERDIR"'/Media/Games/Steam/steamapps/appmanifest_2947440.acf' "$LOWERDIR"'/Media/Games/Steam/steamapps/appmanifest_2947440.acf'
rmdir "$UPPERDIR"'/Media/Games/Steam/steamapps'
rmdir "$UPPERDIR"'/Media/Games/Steam'
rmdir "$UPPERDIR"'/Media/Games'
rmdir "$UPPERDIR"'/Media'
