#!/usr/bin/env bash
set -x
# This shell script is generated by overlayfs-tools on Sat Nov  1 16:50:15 2025

LOWERDIR='/mnt/winOverlay/SSD2WinLower'
UPPERDIR='/mnt/NVME0/NTFSOverlays/SSD2WinUpper'
chmod --reference "$UPPERDIR"'' "$LOWERDIR"''
chmod --reference "$UPPERDIR"'/SteamLibrary' "$LOWERDIR"'/SteamLibrary'
rm -rf "$LOWERDIR"'/SteamLibrary/libraryfolder.vdf'
mv -T "$UPPERDIR"'/SteamLibrary/libraryfolder.vdf' "$LOWERDIR"'/SteamLibrary/libraryfolder.vdf'
rmdir "$UPPERDIR"'/SteamLibrary'
