#!/usr/bin/env bash
set -x
# This shell script is generated by overlayfs-tools on Mon Oct 20 13:35:23 2025

LOWERDIR='/mnt/winOverlay/SSD2WinLower'
UPPERDIR='/mnt/winOverlay/SSD2WinUpper'
chmod --reference "$UPPERDIR"'' "$LOWERDIR"''
rm -rf "$LOWERDIR"'/SteamLibrary/steamapps/appmanifest_814380.acf'
mv -T "$UPPERDIR"'/SteamLibrary/steamapps/appmanifest_814380.acf' "$LOWERDIR"'/SteamLibrary/steamapps/appmanifest_814380.acf'
rmdir "$UPPERDIR"'/SteamLibrary/steamapps'
rmdir "$UPPERDIR"'/SteamLibrary'
